apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydocker
  template:
    metadata:
      labels:
        app: mydocker
    spec:
      containers:
      - name: mydocker
        image: psesham/mydocker:latest
        ports:
        - containerPort: 8080
