apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: mydocker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Change to "NodePort" for local testing
